name: Alerts
on:
  workflow_run:
    workflows: [Go]
    types: [completed]

jobs:
  on_push_failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'push' && ( github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'master')
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          event: push
          commit: ${{ github.sha }}
          commit_url: https://github.com/Mo-Fatah/test-alerts/commit/${{ github.sha }}
          author: ${{ github.actor }}
          workflow_name: ${{ github.event.workflow_run.name }}
          workflow_url: ${{ github.event.workflow_run.html_url}}

  on_pull_request_failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          event: pr
          commit: ${{ github.sha }}
          commit_url: https://github.com/Mo-Fatah/test-alerts/commit/${{ github.sha }}
          author: ${{ github.actor }}
          workflow_name: ${{ github.event.workflow_run.name }}
          workflow_url: ${{ github.event.workflow_run.html_url}}
          users_path: ${{github.workspace}}/.github/slack-alerts/github-to-slack