name: Alerts
on:
  workflow_run:
    workflows: [Go]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          event: pr