name: Alerts
on:
  workflow_run:
    workflows: [Go]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        with: 
          webhook: https://hooks.slack.com/services/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
          event: pr
        env: 
          webhook: https://hooks.slack.com/services/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
          event: pr