name: Alerts
on:
  workflow_run:
    workflows: [Go]
    types: [completed]

jobs:
  on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          event: push