name: Alerts
on:
  workflow_run:
    workflows: [Go]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: Mo-Fatah/ci-alerts@v1