name: Alerts
on:
  workflow_run:
    workflows: [Go]
    types: [completed]

jobs:
  on_push_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event_name == 'push' }} 
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          event: push
          commit: ${{ github.sha }}
          commit_url: https://github.com/Mo-Fatah/test-alerts/commit/${{ github.sha }}
          author: ${{ github.actor }}
          workflow_name: ${{ github.event.workflow_run.name }}
          workflow_url: ${{ github.event.workflow_run.html_url}}