name: Alerts
on:
  workflow_run:
    workflows: [Go]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Mo-Fatah/ci-alerts@main
        env: 
          webhook: https://hooks.slack.com/services/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
          event: pr